services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf@sha256:f54b9ed9c56b767e0098b525468206689b666323c2b500b9686c3cf41cdfa348
    container_name: bentopdf
    restart: unless-stopped

    ports:
      - "9000:8080"

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
