version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser@sha256:0effd18992e8bd895649df97304bf69806e75ab94a5d75fce82d7276bd6067ab
    container_name: filebrowser

    ports:
      - "8080:80"

    volumes:
      - /data/files:/srv
      - /home/madmax/stacks/file-browser/config:/config
      - /home/madmax/stacks/file-browser/database:/database

    restart: unless-stopped
