version: "3.8"

services:
  filebrowser:
    user: "1000:1001"
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8080:80"
    volumes:
      - /data/files:/srv
      - ./filebrowser/database:/database
      - ./filebrowser/config:/config
    restart: unless-stopped

volumes:
  filebrowser_data:
  filebrowser_database:
  filebrowser_config:
